HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html
Refresh: 600

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>openSUSE Service Down</title>
  <link type="text/css" rel="stylesheet" href="https://static.opensuse.org/chameleon-3.0/dist/css/chameleon.css" />
  <link href="/favicon.ico" rel="shortcut icon" />
  <meta name="description" content="This openSUSE service is currently down">
  <link rel="shortcut icon" type="image/x-icon" href="https://static.opensuse.org/favicon.ico">
  <meta name="theme-color" content="#73ba25">
  <meta property="og:site_name" content="openSUSE service downtime">
  <meta property="og:title" content="openSUSE service downtime">
  <meta property="og:description" content="This openSUSE service is currently down">
  <meta property="og:url" content="https://www.opensuse.org">
  <meta property="og:image" content="https://static.opensuse.org/favicon-192.png">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="openSUSE service down">
  <meta name="twitter:url" content="https://www.opensuse.org">
  <meta name="keywords" content="openSUSE service down" />
  <meta name="author" content="openSUSE project" />
  <meta name="robots" content="index,follow" />
  <script src="https://static.opensuse.org/chameleon-3.0/dist/js/jquery.slim.js"></script>
  <script src="https://static.opensuse.org/chameleon-3.0/dist/js/bootstrap.bundle.js"></script>
  <script src="https://static.opensuse.org/chameleon-3.0/dist/js/chameleon.js"></script>
</head>
<body class="d-flex flex-column">
  <nav class="navbar noprint navbar-expand-md sticky-top">
    <a class="navbar-brand" href="/">
      <img src="https://static.opensuse.org/favicon.svg" class="d-inline-block align-top" alt="openSUSE"
        width="30" height="30"/>
      <span class="navbar-title">Service down</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse">
      <svg width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z">
        </path>
      </svg>
    </button>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav mr-auto flex-md-shrink-0">
	      <li class="nav-item"><a class="nav-link" href="https://www.opensuse.org/">Homepage</a></li>
	      <li class="nav-item"><a class="nav-link" href="https://status.opensuse.org/">Service status overview</a></li>
      </ul>
    </div>

    <button class="navbar-toggler megamenu-toggler" type="button" data-toggle="collapse" data-target="#megamenu"
      aria-expanded="true">
      <svg class="bi bi-grid" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
        xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z">
        </path>
      </svg>
    </button>

  </nav>

  <div id="megamenu" class="megamenu collapse"></div>
  <main class="page-content flex-fill" aria-label="Content">
    <div class="container py-3">
      <p class="alert alert-danger">We are very sorry, but the requested service is currently not available.</p>
      <p class="alert alert-warning">Please check our <a href="https://status.opensuse.org/">Status page</a>, if the problem is already known.</p>
      <p class="alert alert-info">Note: we have a regular maintenance window each Thursday, from 08:00 - 10:00 CET. More information about this maintenance window is provided in the <a href="https://en.opensuse.org/openSUSE:Downtime">openSUSE wiki</a>.</p>


      <p><img src="https://en.opensuse.org/images/4/43/Failgeeko.png" alt="Go grab some coffee meanwhile"/></p>
</body>
</html>
