HTTP/1.0 200
Cache-Control: no-cache
Connection: close
Content-Type: text/plain
X-Via: {{ grains.host }}

# Our security address
Contact: https://www.suse.com/support/security/contact/
# Our OpenPGP key
Encryption: https://www.suse.com/support/security/contact/
# We don't expect the above to change, therefore...
Expires: 2099-12-31T23:00:00.000Z
