include:
  - profile.accounts
  - profile.apparmor
  - profile.cron
  - profile.etckeeper
  - profile.ldap.client
  - profile.log
  - profile.monitoring
  - profile.postfix
  - profile.regional
  - infrastructure.salt.minion
  - profile.sysctl
  - zypper
