# yamllint disable rule:line-length
#####################################################
## MANAGED BY SALT in salt/files/prometheus/alerts ##
#####################################################
---
groups:
  - name: ioo-mail-virtual-users
    rules:
      - alert: Member aliases update failed
        expr: >-
          virtual_opensuse_users_status > 0
        for: 5s
        labels:
          severity: warning
        annotations:
          title: >-
            Failed to update member aliases on {{ $labels.instance }}
          description: >-
            Failed to update member aliases through get_member_aliases on {{ $labels.instance }}.

      - alert: Member aliases update failed due to too many removals
        expr: >-
          virtual_opensuse_users_remove > 0
          and on(instance)
          virtual_opensuse_users_status > 0
        for: 5s
        labels:
          severity: critical
        annotations:
          title: >-
            Failed to update member aliases on {{ $labels.instance }}
          description: >-
            Failed to update member aliases through get_member_aliases on {{ $labels.instance }}, would have removed {{ $value }} entries.
