# yamllint disable rule:line-length
#####################################################
## MANAGED BY SALT in salt/files/prometheus/alerts ##
#####################################################
---
groups:
  - name: ioo-mysql
    rules:
      - alert: MySQLDown
        expr: mysql_up == 0
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: MySQL on instance {{ $labels.instance }} is down
          description: "MySQL instance is down on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: GaleraFragile
        expr: sum(mysql_up{instance=~"galera[1-3].infra.opensuse.org"}) < 3
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: Less than three Galera nodes are online
          description: "Cluster is fragile - ensure at least two nodes stay online!\n  VALUE = {{ $value }}"
      - alert: MySQLTooManyConnections
        expr: max_over_time(mysql_global_status_threads_connected[1m]) / mysql_global_variables_max_connections * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: MySQL too many connections (> 80%) on instance {{ $labels.instance }}
          description: "More than 80% of MySQL connections are in use on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MySQLSlowQueries
        expr: increase(mysql_global_status_slow_queries[1m]) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Slow MySQL queries on instance {{ $labels.instance }})
          description: "MySQL server {{ $labels.instance }} has some new slow query.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MySQLInnodbLogWaits
        expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: MySQL InnoDB log waits on instance {{ $labels.instance }})
          description: "MySQL innodb log writes on {{ $labels.instance }} are stalling\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MySQLRestarted
        expr: mysql_global_status_uptime < 300
        for: 0m
        labels:
          severity: info
        annotations:
          summary: MySQL server restarted on instance {{ $labels.instance }})
          description: "MySQL server on {{ $labels.instance }} has been restarted less than five minutes ago.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
