# yamllint disable rule:line-length
#####################################################
## MANAGED BY SALT in salt/files/prometheus/alerts ##
#####################################################
---
groups:
  - name: ioo-prometheus
    rules:
      - alert: PrometheusDown
        expr: up{job="prometheus"} != 1
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: Prometheus master is down (instance {{ $labels.instance }})
          description: |+
            Prometheus is down and no long monitoring
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusConfigurationReloadFailure
        expr: prometheus_config_last_reload_successful != 1
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: Prometheus configuration reload failure (instance {{ $labels.instance }})
          description: |+
            Prometheus configuration reload error
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusDeadManSwitch
        expr: vector(1)
        for: 0s
        labels:
          severity: none
        annotations:
          summary: Prometheus dead man switch
          description: This is an always firing alert. It is used as a health check for alerting systems.
      - alert: PrometheusNotConnectedToAlertmanager
        expr: prometheus_notifications_alertmanagers_discovered < 1
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: Prometheus not connected to Alertmanager (instance {{ $labels.instance }})
          description: |+
            Prometheus is not connected to any Alertmanager
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusRuleEvaluationSlow
        expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
        for: 5m
        labels:
          severity: info
        annotations:
          summary: Prometheus rule evaluation slow (instance {{ $labels.instance }})
          description: |+
            Prometheus rule evaluation took more time than the scheduled interval
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusNotificationsBacklog
        expr: min_over_time(prometheus_notifications_queue_length[10m]) > 0
        for: 5m
        labels:
          severity: info
        annotations:
          summary: Prometheus notifications backlog (instance {{ $labels.instance }})
          description: |+
            The Prometheus notification queue has not been empty for 5 minutes
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusTsdbReloadFailures
        expr: increase(prometheus_tsdb_reloads_failures_total[1m]) > 0
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: Prometheus TSDB reload failures (instance {{ $labels.instance }})
          description: |+
            Prometheus encountered {{ $value }} TSDB reload failures
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusTsdbWalCorruptions
        expr: increase(prometheus_tsdb_wal_corruptions_total[1m]) > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: Prometheus TSDB WAL corruptions (instance {{ $labels.instance }})
          description: |+
            Prometheus encountered {{ $value }} TSDB WAL corruptions
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
      - alert: PrometheusTsdbWalTruncationsFailed
        expr: increase(prometheus_tsdb_wal_truncations_failed_total[1m]) > 0
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: Prometheus TSDB WAL truncations failed (instance {{ $labels.instance }})
          description: |+
            Prometheus encountered {{ $value }} TSDB WAL truncation failures
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
