# yamllint disable rule:line-length
#####################################################
## MANAGED BY SALT in salt/files/prometheus/alerts ##
#####################################################
---
groups:
  - name: ioo-smart
    rules:
      - alert: SMART Exporter Failure
        expr: smartctl_device_smartctl_exit_status > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: >-
            SMART: smartctl failure ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            The smartctl exporter failed to execute smartctl for {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      - alert: SMART Failures
        expr: smartctl_device_smart_status == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: >-
            SMART: Bad status ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART did not pass for disk {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      - alert: SMART High Device Temperature
        expr: smartctl_device_temperature > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: >-
            SMART: High disk temperature ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART reports an unusually high disk temperature for disk device {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      - alert: SMART Very High Device Temperature
        expr: smartctl_device_temperature > 70
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: >-
            SMART: Critical disk temperature ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART reports a critically high disk temperature for disk device {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      ## Rules below only apply to NVMe disks

      - alert: SMART NVMe Critical Warnings
        expr: smartctl_device_critical_warning > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: >-
            SMART: Critical warnings ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART reports critical warnings for the NVMe device {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      - alert: SMART NVMe Media Errors
        expr: smartctl_device_media_errors > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: >-
            SMART: Media errors ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART reports media errors for the NVMe device {{ $labels.device }} on {{ $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

      - alert: SMART NVMe Wearout
        expr: >-
          smartctl_device_available_spare{device=~"nvme.*"}
          <
          smartctl_device_available_spare_threshold{device=~"nvme.*"}
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: >-
            SMART: NVME wearout ({{ $labels.device }}/{{ $labels.instance }})
          description: |
            SMART reports the NVMe device {{ $labels.device }} on {{ $labels.instance }} to be wearing out.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
