---
atlas1.infra.opensuse.org:
  targets:
    - host: atlas1
      services:
        - haproxy
atlas2.infra.opensuse.org:
  targets:
    - host: atlas2
      services:
        - haproxy
code-dev.infra.opensuse.org:
  targets:
    - host: code-dev
      services:
        - forgejo
download.infra.opensuse.org:
  sans:
    - download-prg.infra.opensuse.org
  targets:
    - host: download
      services:
        - nginx
git.infra.opensuse.org:
  sans:
    - gitlab.infra.opensuse.org
  targets:
    - host: mickey
      services:
        - nginx
globus1.infra.opensuse.org:
  targets:
    - host: globus1
      services:
        - haproxy
globus2.infra.opensuse.org:
  targets:
    - host: globus2
      services:
        - haproxy
hel.infra.opensuse.org:
  sans:
    - dbproxy.infra.opensuse.org
    - hel1.infra.opensuse.org
    - hel2.infra.opensuse.org
    - postgresql.infra.opensuse.org
  targets:
    - macro: hel
      services:
        - pgbouncer
idm-ext-dev.infra.opensuse.org:
  targets:
    - macro: hel
idm.infra.opensuse.org:
  sans:
    - ldap.infra.opensuse.org
  targets:
    - macro: hel
kani-ext-dev1.infra.opensuse.org:
  targets:
    - host: kani-ext-dev1
      services:
        - kanidmd
kani-ext-dev2.infra.opensuse.org:
  targets:
    - host: kani-ext-dev2
      services:
        - kanidmd
kani1.infra.opensuse.org:
  targets:
    - host: kani1
      services:
        - kanidmd
kani2.infra.opensuse.org:
  targets:
    - host: kani2
      services:
        - kanidmd
matrix.infra.opensuse.org:
  targets:
    - host: matrix
      services:
        - nginx
monitor.infra.opensuse.org:
  sans:
    - alertmanager.infra.opensuse.org
    - alerts.infra.opensuse.org
    - karma.infra.opensuse.org
    - prometheus.infra.opensuse.org
  targets:
    - host: monitor
      services:
        - apache2
mybackup.infra.opensuse.org:
  targets:
    - host: mybackup
      services:
        - mariadb
mysql.infra.opensuse.org:
  sans:
    - galera.infra.opensuse.org
    - mariadb.infra.opensuse.org
  targets:
    - macro: galera
netbox.infra.opensuse.org:
  targets:
    - macro: hel
netbox1.infra.opensuse.org:
  targets:
    - host: netbox1
      services:
        - apache2
quiz.infra.opensuse.org:
  targets:
    - host: quiz
      services:
        - nginx
seidr1.infra.opensuse.org:
  sans:
    - salt.infra.opensuse.org
    - seidr.infra.opensuse.org
  targets:
    - host: seidr1
      services:
        - salined
        - salt-api
tyr.infra.opensuse.org:
  sans:
    - tyr1.infra.opensuse.org
    - tyr2.infra.opensuse.org
  targets:
    - macro: tyr
volva-nw1.infra.opensuse.org:
  sans:
    - volva-nw.infra.opensuse.org
  targets:
    - host: volva-nw1
      services:
        - salined
        - salt-api
volva1.infra.opensuse.org:
  sans:
    - salt.infra.opensuse.org
    - volva.infra.opensuse.org
  targets:
    - host: volva1
      services:
        - salined
        - salt-api
volva2.infra.opensuse.org:
  sans:
    - salt.infra.opensuse.org
    - volva.infra.opensuse.org
  targets:
    - host: volva2
      services:
        - salined
        - salt-api
witch1.infra.opensuse.org:
  sans:
    - salt.infra.opensuse.org
    - witch.infra.opensuse.org
  targets:
    - host: witch1
      services:
        - salined
        - salt-api
