---
download.infra.opensuse.org:
  sans:
    - download-prg.infra.opensuse.org
  targets:
    - host: download
      services:
        - nginx
git.infra.opensuse.org:
  sans:
    - gitlab.infra.opensuse.org
  targets:
    - host: mickey
      services:
        - nginx
hel.infra.opensuse.org:
  sans:
    - dbproxy.infra.opensuse.org
    - hel1.infra.opensuse.org
    - hel2.infra.opensuse.org
    - mysql.infra.opensuse.org
    - postgresql.infra.opensuse.org
  targets:
    - macro: hel
      services:
        - pgbouncer
idm.infra.opensuse.org:
  sans:
    - ldap.infra.opensuse.org
  targets:
    - macro: hel
kani1.infra.opensuse.org:
  targets:
    - host: kani1
      services:
        - kanidmd
kani2.infra.opensuse.org:
  targets:
    - host: kani2
      services:
        - kanidmd
monitor.infra.opensuse.org:
  sans:
    - alertmanager.infra.opensuse.org
    - alerts.infra.opensuse.org
    - karma.infra.opensuse.org
    - prometheus.infra.opensuse.org
  targets:
    - host: monitor
      services:
        - apache2
netbox.infra.opensuse.org:
  targets:
    - macro: hel
netbox1.infra.opensuse.org:
  targets:
    - host: netbox1
      services:
        - apache2
witch1.infra.opensuse.org:
  sans:
    - salt.infra.opensuse.org
    - witch.infra.opensuse.org
  targets:
    - host: witch1
      services:
        - salined
        - salt-api
