---
atlas:
  hosts:
    - atlas1
    - atlas2
  services:
    - haproxy
galera:
  hosts:
    - galera1
    - galera2
    - galera3
  services:
    - mariadb
globus:
  hosts:
    - globus1
    - globus2
  services:
    - haproxy
hel:
  hosts:
    - hel1
    - hel2
  services:
    - haproxy
mx:
  hosts:
    - mx1
    - mx2
  services:
    - postfix
mx-test:
  hosts:
    - mx-test
  services:
    - postfix
stage:
  hosts:
    - stage3
  services:
    - apache2
    - nginx
status:
  hosts:
    - status1
    - status3
  services:
    - apache2
tyr:
  hosts:
    - tyr1
    - tyr2
  services:
    - haproxy
