#!/bin/sh
{{ pillar['managed_by_salt'] }}

tmp=$(mktemp -p /tmp -d memberaliases.XXXXXXXXXX)
cd "$tmp" || exit 1

metrics_base='virtual_opensuse_users'

write_metrics() {
  {
    printf '%s_status %i\n' "$metrics_base" "$1"
    printf '%s_add %i\n'    "$metrics_base" "$2"
    printf '%s_remove %i\n' "$metrics_base" "$3"
    printf '%s_total %i\n'  "$metrics_base" "$4"
  } | sponge /var/spool/prometheus/get_member_aliases.prom
}

mysql -h mysql.infra.opensuse.org -P3307 -Dmembers -NB -e 'select addr, email_target from email_aliases' >member.aliases.new

# need to make sure it is ordered
LC_ALL=C sort -d -k1 member.aliases.new >member.aliases.ordered

added=$(diff -B -b /etc/postfix/virtual-opensuse-users member.aliases.ordered | grep ^\> | wc -l)
removed=$(diff -B -b /etc/postfix/virtual-opensuse-users member.aliases.ordered | grep ^\< | wc -l)
total=$(wc -l <member.aliases.ordered)

# if too many would be removed, something's probably wrong.
if test $removed -gt 20
then
        printf "New member-aliases list (%u entries) would remove %u aliases ?\n" $total $removed
        write_metrics '1' "$added" "$removed" "$total"
        # tidy up
        rm -Rf "$tmp"
        exit 1
fi

# if we had any changes, update our alias list
if test $added -gt 0 -o $removed -gt 0
then
        printf "virtual-opensuse-users updated: %u additions, %u removals, now %u entries\n" $added $removed $total
        write_metrics '0' "$added" "$removed" "$total"
        # debug
        diff -B -b /etc/postfix/virtual-opensuse-users member.aliases.ordered

        mv member.aliases.ordered /etc/postfix/virtual-opensuse-users
        postmap /etc/postfix/virtual-opensuse-users
        postfix reload
else
#        printf "virtual-opensuse-users not updated, no changes found.\n"
        write_metrics '0' "$added" "$removed" "$total"
fi

# tidy up
rm -Rf "$tmp"
