#!/bin/sh
#
# 2016/03/03 from http://www.postfix.org/FORWARD_SECRECY_README.html#server_fs
# 
openssl dhparam -out dh512.tmp 512   2>/dev/null && mv dh512.tmp dh512.pem
openssl dhparam -out dh1024.tmp 1024 2>/dev/null && mv dh1024.tmp dh1024.pem
openssl dhparam -out dh2048.tmp 2048 2>/dev/null && mv dh2048.tmp dh2048.pem
chmod 644 dh512.pem dh1024.pem dh2048.pem

