#!/bin/bash
{% set deploy_password = salt['pillar.get']('profile:salt:reactor:update_fileserver_deploy_password', '') %}
salt-call event.fire_master {{ deploy_password }} salt/fileserver/gitfs/update
