production:
  adapter: postgresql
  encoding: unicode
  database: "{{ pillar['profile']['paste']['database_name'] }}"
  username: "{{ pillar['profile']['paste']['database_user'] }}"
  password: "{{ pillar['postgres']['users']['paste']['password'] }}"
  host: "{{ pillar['profile']['paste']['database_host'] }}"
