production:
  program_name: openSUSE Paste
  theme: openSUSE
  authentication:
    openid_connect:
      name: :openid_connect
      discovery: true
      issuer: https://id.opensuse.org/openidc/
      scope:
      - :openid
      - :email
      - :profile
      response_type: :code
      uid_field: preferred_username
      client_options:
        port: 443
        scheme: https
        host: id.opensuse.org
        identifier: "{{ pillar['profile']['paste']['openidc']['client_id'] }}"
        secret: "{{ pillar['profile']['paste']['openidc']['secret'] }}"
        redirect_uri: https://paste.opensuse.org/auth/openid_connect/callback
  sign_up_link: "https://idp-portal.suse.com/univention/self-service/#page=createaccount"
