---
orbit:
  nodes:
    - orbit20
    - orbit21
  storage: local
squanchy:
  nodes:
    - squanchy
  storage: local
falkor:
  nodes:
    - falkor20
    - falkor21
    - falkor22
  primary_node: falkor20.infra.opensuse.org
  netapp: {#- to-do: manage NetApp storage #}
    host: None
    vs_primary: vs_opensuse
    igroup_primary: falkor
  storage: san
