---
- infra.opensuse.org
- opensuse.asia
- opensuse.bar
- opensuse.co
- opensuse.co.in
- opensuse.com
- opensuse.com.br
- opensuse.com.es
- opensuse.com.mx
- opensuse.de
- opensuse.eu
- opensuse.fr
- opensuse.gen.tr
- opensuse.jp
- opensuse.kr
- opensuse.me
- opensuse.mu
- opensuse.mx
- opensuse.net
- opensuse.org
- opensuse.org.cn
- opensuse.pk
- opensuse-project.com
- opensuse-project.de
- opensuse-project.net
- opensuse-project.org
- e.7.2.b.0.4.e.d.7.0.a.2.ip6.arpa
- 3.0.2.1.e.7.2.b.0.4.e.d.7.0.a.2.ip6.arpa
- 4.0.2.1.e.7.2.b.0.4.e.d.7.0.a.2.ip6.arpa
- 48/28.223.135.195.in-addr.arpa
- 16.172.in-addr.arpa
