asgard1:
  cluster: orbit
  node: orbit20.infra.opensuse.org
  ram: 4096MB
  vcpu: 4
  interfaces:
    eth0:
      source: bond-fib
      mac: 'd2:e1:4b:98:46:1f'
  disks:
    root: 20G
  image: admin-micro-5_4
asgard2:
  cluster: orbit
  node: orbit21.infra.opensuse.org
  ram: 4096MB
  vcpu: 4
  interfaces:
    eth0:
      source: bond-fib
      mac: 'd2:e1:4b:98:46:2f'
  disks:
    root: 20G
  image: admin-micro-5_4
witch1:
  cluster: squanchy
  ram: 4096MB
  vcpu: 4
  interfaces:
    eth0:
      source: x-os-internal
      mac: '92:93:ee:1a:c4:80'
      # to-do: drop IPv4 once all machines in remote locations can reach the Salt Master via IPv6
      ip4: 172.16.129.2/24
      ip6: 2a07:de40:b27e:1203::a/64
  disks:
    root: 15G
  image: admin-minimal-15_5
warp:
  cluster: squanchy
  ram: 512MB
  vcpu: 1
  interfaces:
    eth0:
      source: x-os-s-warp
      mac: 'd6:f7:c1:31:ce:80'
      ip6: 2a07:de40:b27e:1101::2/64
    eth1:
      source: x-s-j-os-out
      mac: 'd6:f7:c1:31:ce:81'
      ip4: 10.151.202.1/24
      ip6: 2a07:de40:b27f:202::1/64
  disks:
    root: 15G
  image: admin-minimal-15_5
devcon:
  cluster: squanchy
  ram: 512MB
  vcpu: 1
  interfaces:
    eth0:
      source: x-os-internal
      mac: '1a:eb:8a:3d:1a:80'
      ip6: 2a07:de40:b27e:1203::de/64
    eth1:
      source: x-os-ipmi-ur
      mac: '1a:eb:8a:3d:1a:81'
      ip6: fd4b:5292:d67e:1001::de/64
  disks:
    root: 15G
  image: admin-minimal-15_5
atlas1:
  cluster: falkor
  ram: 4096MB
  vcpu: 2
  primary_interface: os-public
  interfaces:
    os-public:
      source: x-os-public
      mac: '2e:b6:1e:18:39:68'
      ip4: 172.16.130.11/24
      ip6: 2a07:de40:b27e:1204::11/64
  disks:
    root: 3600a09803831494f635d554b394f7730
atlas2:
  cluster: falkor
  ram: 4096MB
  vcpu: 2
  primary_interface: os-public
  interfaces:
    os-public:
      source: x-os-public
      mac: '2e:b6:1e:18:39:69'
      ip4: 172.16.130.12/24
      ip6: 2a07:de40:b27e:1204::12/64
  disks:
    root: 3600a09803831494f635d554b394f7731
narwal8:
  cluster: falkor
  ram: 1024MB
  vcpu: 1
  primary_interface: internal
  interfaces:
    internal:
      source: x-os-internal
      mac: '2e:09:0d:dc:6e:14'
      ip6: 2a07:de40:b27e:1203::e8/64
  disks:
    root: 3600a09803831494f635d554b394f7739
