---
prg2:
  openSUSE-thor:
    export: true
    short: os-thor
    net6: 2a07:de40:b27e:1100::/64
    gw6: '2a07:de40:b27e:1100::3'
    id: 1100
  openSUSE-SUSE-warp:
    short: os-s-warp
    net6: 2a07:de40:b27e:1101::/64
    gw6: '2a07:de40:b27e:1101::3'
    id: 1101
  openSUSE-odin:
    short: os-odin
    net6: 2a07:de40:b27e:1102::/64
    gw6: 2a07:de40:b27e:1102::3
    net4: 172.16.202.0/24
    gw4:
      gw_vip: 172.16.202.3
    id: 1102
  openSUSE-salt:
    export: true
    short: os-salt
    net6: 2a07:de40:b27e:1200::/64
    gw6: '2a07:de40:b27e:1200::3'
    id: 1200
  openSUSE-bare:
    short: os-bare
    net6: 2a07:de40:b27e:1201::/64
    gw6: '2a07:de40:b27e:1201::3'
    id: 1201
  openSUSE-ipmi-r:
    short: os-ipmi-r
    net6: 2a07:de40:b27e:1202::/64
    gw6: '2a07:de40:b27e:1202::3'
    id: 1202
  openSUSE-internal:
    export: true
    short: os-internal
    net6: 2a07:de40:b27e:1203::/64
    gw6: '2a07:de40:b27e:1203::3'
    id: 1203
  openSUSE-public:
    short: os-public
    net6: 2a07:de40:b27e:1204::/64
    gw6: '2a07:de40:b27e:1204::3'
    net4: 172.16.130.0/24
    gw4:
      gw_vip: 172.16.130.3
    id: 1204
  openSUSE-mirror:
    export: true
    short: os-mirror
    net6: 2a07:de40:b27e:1205::/64
    gw6: '2a07:de40:b27e:1205::3'
    id: 1205
  openSUSE-code:
    short: os-code
    net6: 2a07:de40:b27e:1206::/64
    gw6: 2a07:de40:b27e:1206::3
    id: 1206
  openSUSE-GHR-Cobbler:
    short: os-ghr-c
    net6: 2a07:de40:b27e:1207::/64
    gw6: 2a07:de40:b27e:1207::3
    id: 1207
  openSUSE-GHR-openSUSE:
    short: os-ghr-os
    net6: 2a07:de40:b27e:1208::/64
    gw6: 2a07:de40:b27e:1208::3
    id: 1208
  openSUSE-mail:
    short: os-mail
    net6: 2a07:de40:b27e:1209::/64
    gw6: 2a07:de40:b27e:1209::3
    net4: 172.16.131.0/24
    gw4:
      gw_vip: 172.16.131.3
    id: 1209
  openSUSE-kani:
    short: os-kani
    net6: 2a07:de40:b27e:1210::/64
    gw6: 2a07:de40:b27e:1210::3
    id: 1210
  openSUSE-netbox:
    short: os-netbox
    net6: 2a07:de40:b27e:1211::/64
    gw6: 2a07:de40:b27e:1211::3
    id: 1211
  openSUSE-log:
    short: os-log
    net6: 2a07:de40:b27e:1215::/64
    gw6: 2a07:de40:b27e:1215::3
    id: 1215

slc1:
  openSUSE-bare:
    export: true
    short: os-bare
    net6: 2a07:de40:617e:1800::/64
    gw6: 2a07:de40:617e:1800::3
    id: 1800
  openSUSE-devcon:
    export: true
    short: os-devcon
    net6: 2a07:de40:617e:1801::/64
    gw6: 2a07:de40:617e:1801::3
    id: 1801
  openSUSE-sif:
    export: true
    short: os-sif
    net6: 2a07:de40:617e:1802::/64
    gw6: 2a07:de40:617e:1802::3
    id: 1802
  openSUSE-SUSE-warp:
    export: true
    short: os-s-warp
    net6: 2a07:de40:617e:1803::/64
    gw6: 2a07:de40:617e:1803::3
    id: 1803
  openSUSE-salt:
    export: true
    short: os-salt
    net6: 2a07:de40:617e:1900::/64
    gw6: 2a07:de40:617e:1900::3
    id: 1900
  openSUSE-internal:
    export: true
    short: os-internal
    net6: 2a07:de40:617e:1903::/64
    gw6: 2a07:de40:617e:1903::3
    id: 1903
  openSUSE-public:
    export: true
    short: os-public
    net6: 2a07:de40:617e:1904::/64
    gw6: 2a07:de40:617e:1904::3
    net4: 172.16.113.0/28
    gw4:
      gw_vip: 172.16.113.3
    id: 1904
  openSUSE-mirror:
    export: true
    short: os-mirror
    net6: 2a07:de40:617e:1905::/64
    gw6: 2a07:de40:617e:1905::3
    id: 1905
  openSUSE-mirrorcache:
    export: true
    short: os-mircache
    net6: 2a07:de40:617e:1906::/64
    gw6: 2a07:de40:617e:1906::3
    id: 1906
  openSUSE-debuginfod:
    export: true
    short: os-dbginfod
    net6: 2a07:de40:617e:1907::/64
    gw6: 2a07:de40:617e:1907::3
    id: 1907

# below are mapping networks and not VLANs
pseudo:
  prg2:
    openSUSE-NAT64-Pool:
      export: true
      net6: 2a07:de40:b27e:64::/96
      net4: 172.16.164.0/24
  slc1:
    openSUSE-NAT64-Pool:
      export: true
      net6: 2a07:de40:617e:64::/96
      net4: 172.16.127.0/25
