---

- asgard1:
    addresses:
      - fd4b:5292:d67e:5::1/127
      - 172.16.201.7/31
    link_local: fe80::216:3eaa:fe51:fd8c/64
    interface: nueqsc_stonehat
    public_key: 'n3NnWpxrm5Jp+lQAsYdMUa6zkpgZGPdIlo7AngptvQM='
  stonehat:
    addresses:
      - fd4b:5292:d67e:5::/127
      - 172.16.201.6/31
    link_local: fe80::216:3edd:fe2c:8cde/64
    interface: prg2_asgard1
    listen: '[2a01:138:a004::210]:52461'
    public_key: 'N9VzRkoVHeGpzSFGGQJP2i600jdoDnq0vzAmxHyz43s='

- asgard2:
    addresses:
      - fd4b:5292:d67e:6::1/127
      - 172.16.202.7/31
    link_local: fe80::216:3ebb:fe51:fd8c/64
    interface: nueqsc_stonehat
    public_key: 'uC+SwUpJFuhw5quP7h3ybdFxtTzsEOmySm8IkTxk0h4='
  stonehat:
    addresses:
      - fd4b:5292:d67e:6::/127
      - 172.16.202.6/31
    link_local: fe80::216:3eee:fe2c:8cde/64
    interface: prg2_asgard2
    listen: '[2a01:138:a004::210]:52462'
    public_key: 'onGTn/HXKclx/oJCQeliRMmEg4SdgvR2NKySsdxzlGk='

- avalon1:
    addresses:
      - fda1:21af:580f:1::/127
      - 172.16.112.0/31
    link_local: fe80::216:3eff:fe10:1a1a/64
    interface: prg2_asgard
    public_key: 'i+2br0nCBmlOfBFLKTNHM6BvzDU1lNVzyK4QmHSwFww='
  asgard1:
    addresses:
      - fda1:21af:580f:1::1/127
      - 172.16.112.1/31
    link_local: fe80::216:3eff:fe10:1a1b/64
    interface: slc1_avalon
    listen: '[2a07:de40:b27f:201::11]:52461'
    public_key: 'rj1TytlWdj9x9bInYl5uEuppWqGxiE2QXy+iaf2pcGc='

- avalon2:
    addresses:
      - fda1:21af:580f:1::2/127
      - 172.16.112.2/31
    link_local: fe80::216:3eff:fe10:1a2a/64
    interface: prg2_asgard
    public_key: 'XeTj4sCoekGX1IK/lNsNxzoYQveCcnVtZ60wCoKVqUA='
  asgard2:
    addresses:
      - fda1:21af:580f:1::3/127
      - 172.16.112.3/31
    link_local: fe80::216:3eff:fe10:1a2b/64
    interface: slc1_avalon
    listen: '[2a07:de40:b27f:201::12]:52461'
    public_key: 'Yv/Wv4kqbBzzAqAuNx5cQHwlbofJLq8WGwxILlI8aSw='

- avalon1:
    addresses:
      - fda1:21af:580f:1::4/127
      - 172.16.112.4/31
    link_local: fe80::216:3eff:fe10:2c2c/64
    interface: nueqsc_stonehat
    listen: '[2a07:de40:617f:201::11]:52462'
    public_key: 'y3pZVSLJQASLHUjgRPxZUnCx5/pmuFJViQopBdWAw00='
  stonehat:
    addresses:
      - fda1:21af:580f:1::5/127
      - 172.16.112.5/31
    link_local: fe80::216:3eff:fe10:2c2d/64
    interface: slc1_avalon1
    public_key: 'HuNMES62YB7aNYZ5ozhE9x8jd95kq4UFAqxb0D5wlTA='

- avalon2:
    addresses:
      - fda1:21af:580f:1::6/127
      - 172.16.112.6/31
    link_local: fe80::216:3eff:fe10:2d2c/64
    interface: nueqsc_stonehat
    listen: '[2a07:de40:617f:201::12]:52462'
    public_key: 'SlsLRIezsE0Y/skI7tzvlZiqSk4OgLOySo04fkb90Cg='
  stonehat:
    addresses:
      - fda1:21af:580f:1::7/127
      - 172.16.112.7/31
    link_local: fe80::216:3eff:fe10:2d2d/64
    interface: slc1_avalon2
    public_key: 'IaGH2k2BS0aKUXn3TZDp2Tl0MZrJnB7RAZk9Z14b7UU='
